#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 Evgeny Kazantsev <exequtic@gmail.com>
# SPDX-License-Identifier: MIT

source "$(dirname "$0")/utils"

declare -A termArg=( ["gnome-terminal"]="--" ["ptyxis"]="--" ["terminator"]="-x" )
term="$(basename $terminal)"
termArg="${termArg[$term]:-"-e"}"
scr="$(dirname "$0")/$1"
arg="${@:2}"

if [[ $term = "yakuake" ]]; then
    session=$(qdbusCMD sessions addSession)
    visible=$(qdbusCMD MainWindow_1 org.qtproject.Qt.QWidget.visible)
    qdbusCMD tabs org.kde.yakuake.setTabTitle $session ${1^}
    qdbusCMD sessions runCommandInTerminal $session "bash -c 'tput sc; clear; $scr $arg'"
    [[ $visible = "false" ]] && qdbusCMD window org.kde.yakuake.toggleWindowState
elif [[ $term = "ghostty" ]]; then
    eval "$term $termArg bash -c \"'$scr $arg'\""
else
    eval "$term $termArg bash -c '\"$scr\" $arg'"
fi
